server:
    port: 8200


spring:
    application:
        name: cache-demo
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/oa?useSSL=false
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
mybatis:
    mapper-locations: classpath:mybatis/mapper/*.xml
    typeAliasesPackage: com.idea.spbdemo.dao.po

logging:
    level:
        com.idea.spbdemo.dao.mapper: debug

eureka:
    client:
        service-url:
            defaultZone: http://127.0.0.1:8761/eureka/
    instance:
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ip-address}:${server.port}
        status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html