server:
    port: 8200


spring:
    application:
        name: cache-demo
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/oa?useSSL=false
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
    # redis数据库（默认为0）
    redis:
      database: 1
      # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      password:
      # 连接池最大连接数（使用负值表示没有限制）
      pool.max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      pool.max-wait: -1
      # 连接池中的最大空闲连接
      pool.max-idle: 8
      # 连接池中的最小空闲连接
      pool.min-idle: 0
      # 连接超时时间（毫秒）
      timeout: 5000
    cache:
      type: redis
      #默认的单位是毫秒
      redis:
        time-to-live: 10000

cache:
  expire-time: 180

mybatis:
    mapper-locations: classpath:mybatis/mapper/*.xml
    type-aliases-package: org.ibase4j.model*
#    typeAliasesPackage: com.idea.spbdemo.dao.po

logging:
    level:
        com.idea.spbdemo.dao.mapper: debug

eureka:
    client:
        service-url:
            defaultZone: http://127.0.0.1:8761/eureka/
    instance:
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ip-address}:${server.port}
        status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html